// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYBtIFXyDHTuMtKPEr4qaKKD56AJ1ZgBI',
    appId: '1:1018934322742:web:62c6df28575a61ed1dda97',
    messagingSenderId: '1018934322742',
    projectId: 'lifelog-e3d55',
    authDomain: 'lifelog-e3d55.firebaseapp.com',
    storageBucket: 'lifelog-e3d55.firebasestorage.app',
    measurementId: 'G-Y1P3WZX26S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6nIikLuXMMNq-Nc0D6cZSAY7cqTWSzGM',
    appId: '1:1018934322742:android:19d0a94f538457a71dda97',
    messagingSenderId: '1018934322742',
    projectId: 'lifelog-e3d55',
    storageBucket: 'lifelog-e3d55.firebasestorage.app',
  );
}
